/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bridge from"./bridge/index.js";
export type { bridge };
import type * as libraries from"./libraries/index.js";
export type { libraries };
import type * as nodeInterface from"./node-interface/index.js";
export type { nodeInterface };
import type * as precompiles from"./precompiles/index.js";
export type { precompiles };
