/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as arowanaSol from"./Arowana.sol/index.js";
export type { arowanaSol };
import type * as erc20MockSol from"./ERC20Mock.sol/index.js";
export type { erc20MockSol };
