/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc20Sol from"./IERC20.sol/index.js";
export type { ierc20Sol };
import type * as iGatewaySol from"./IGateway.sol/index.js";
export type { iGatewaySol };
import type * as iInitializableProxySol from"./IInitializableProxy.sol/index.js";
export type { iInitializableProxySol };
