/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common.js";

export interface GreeterInterface extends Interface {
  getFunction(nameOrSignature: "greet" | "setGreeting"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "NewGreeting"): EventFragment;

  encodeFunctionData(functionFragment: "greet", values?: undefined): string;
  encodeFunctionData(functionFragment: "setGreeting", values: [string]): string;

  decodeFunctionResult(functionFragment: "greet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setGreeting",
    data: BytesLike,
  ): Result;
}

export namespace NewGreetingEvent {
  export type InputTuple = [greeting: string];
  export type OutputTuple = [greeting: string];
  export interface OutputObject {
    greeting: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Greeter extends BaseContract {
  connect(runner?: ContractRunner | null): Greeter;
  waitForDeployment(): Promise<this>;

  interface: GreeterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  greet: TypedContractMethod<[], [string], "view">;

  setGreeting: TypedContractMethod<[_greeting: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: "greet",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setGreeting",
  ): TypedContractMethod<[_greeting: string], [void], "nonpayable">;

  getEvent(
    key: "NewGreeting",
  ): TypedContractEvent<
    NewGreetingEvent.InputTuple,
    NewGreetingEvent.OutputTuple,
    NewGreetingEvent.OutputObject
  >;

  filters: {
    "NewGreeting(string)": TypedContractEvent<
      NewGreetingEvent.InputTuple,
      NewGreetingEvent.OutputTuple,
      NewGreetingEvent.OutputObject
    >;
    NewGreeting: TypedContractEvent<
      NewGreetingEvent.InputTuple,
      NewGreetingEvent.OutputTuple,
      NewGreetingEvent.OutputObject
    >;
  };
}
