/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as arbGatewaySol from"./ArbGateway.sol/index.js";
export type { arbGatewaySol };
import type * as arbGatewaySettleSol from"./ArbGatewaySettle.sol/index.js";
export type { arbGatewaySettleSol };
import type * as greeterSol from"./Greeter.sol/index.js";
export type { greeterSol };
import type * as greeterChildSol from"./GreeterChild.sol/index.js";
export type { greeterChildSol };
import type * as greeterParentSol from"./GreeterParent.sol/index.js";
export type { greeterParentSol };
