/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGasRefunder,
  IGasRefunderInterface,
} from "../../../../../../@arbitrum/nitro-contracts/src/libraries/IGasRefunder.sol/IGasRefunder.js";

const _abi = [
  {
    inputs: [
      {
        internalType: "address payable",
        name: "spender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "gasUsed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "calldataSize",
        type: "uint256",
      },
    ],
    name: "onGasSpent",
    outputs: [
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGasRefunder__factory {
  static readonly abi = _abi;
  static createInterface(): IGasRefunderInterface {
    return new Interface(_abi) as IGasRefunderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null,
  ): IGasRefunder {
    return new Contract(address, _abi, runner) as unknown as IGasRefunder;
  }
}
