/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as arowanaSol from "./Arowana.sol/index.js";
export * as erc20MockSol from "./ERC20Mock.sol/index.js";
