/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common.js";

export interface GreeterParentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "childTarget"
      | "greet"
      | "inbox"
      | "setGreeting"
      | "setGreetingInChild"
      | "updateChildTarget",
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "NewGreeting" | "RetryableTicketCreated",
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "childTarget",
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: "greet", values?: undefined): string;
  encodeFunctionData(functionFragment: "inbox", values?: undefined): string;
  encodeFunctionData(functionFragment: "setGreeting", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setGreetingInChild",
    values: [string, BigNumberish, BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "updateChildTarget",
    values: [AddressLike],
  ): string;

  decodeFunctionResult(
    functionFragment: "childTarget",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "greet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "inbox", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setGreeting",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGreetingInChild",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateChildTarget",
    data: BytesLike,
  ): Result;
}

export namespace NewGreetingEvent {
  export type InputTuple = [greeting: string];
  export type OutputTuple = [greeting: string];
  export interface OutputObject {
    greeting: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RetryableTicketCreatedEvent {
  export type InputTuple = [ticketId: BigNumberish];
  export type OutputTuple = [ticketId: bigint];
  export interface OutputObject {
    ticketId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GreeterParent extends BaseContract {
  connect(runner?: ContractRunner | null): GreeterParent;
  waitForDeployment(): Promise<this>;

  interface: GreeterParentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  childTarget: TypedContractMethod<[], [string], "view">;

  greet: TypedContractMethod<[], [string], "view">;

  inbox: TypedContractMethod<[], [string], "view">;

  setGreeting: TypedContractMethod<[_greeting: string], [void], "nonpayable">;

  setGreetingInChild: TypedContractMethod<
    [
      _greeting: string,
      maxSubmissionCost: BigNumberish,
      maxGas: BigNumberish,
      gasPriceBid: BigNumberish,
    ],
    [bigint],
    "payable"
  >;

  updateChildTarget: TypedContractMethod<
    [_childTarget: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: "childTarget",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "greet",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "inbox",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setGreeting",
  ): TypedContractMethod<[_greeting: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGreetingInChild",
  ): TypedContractMethod<
    [
      _greeting: string,
      maxSubmissionCost: BigNumberish,
      maxGas: BigNumberish,
      gasPriceBid: BigNumberish,
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "updateChildTarget",
  ): TypedContractMethod<[_childTarget: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "NewGreeting",
  ): TypedContractEvent<
    NewGreetingEvent.InputTuple,
    NewGreetingEvent.OutputTuple,
    NewGreetingEvent.OutputObject
  >;
  getEvent(
    key: "RetryableTicketCreated",
  ): TypedContractEvent<
    RetryableTicketCreatedEvent.InputTuple,
    RetryableTicketCreatedEvent.OutputTuple,
    RetryableTicketCreatedEvent.OutputObject
  >;

  filters: {
    "NewGreeting(string)": TypedContractEvent<
      NewGreetingEvent.InputTuple,
      NewGreetingEvent.OutputTuple,
      NewGreetingEvent.OutputObject
    >;
    NewGreeting: TypedContractEvent<
      NewGreetingEvent.InputTuple,
      NewGreetingEvent.OutputTuple,
      NewGreetingEvent.OutputObject
    >;

    "RetryableTicketCreated(uint256)": TypedContractEvent<
      RetryableTicketCreatedEvent.InputTuple,
      RetryableTicketCreatedEvent.OutputTuple,
      RetryableTicketCreatedEvent.OutputObject
    >;
    RetryableTicketCreated: TypedContractEvent<
      RetryableTicketCreatedEvent.InputTuple,
      RetryableTicketCreatedEvent.OutputTuple,
      RetryableTicketCreatedEvent.OutputObject
    >;
  };
}
