/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as initializableProxySol from"./InitializableProxy.sol/index.js";
export type { initializableProxySol };
