/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc1967 from"./ERC1967/index.js";
export type { erc1967 };
import type * as proxySol from"./Proxy.sol/index.js";
export type { proxySol };
import type * as beacon from"./beacon/index.js";
export type { beacon };
