/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFeeTokenPricer,
  IFeeTokenPricerInterface,
} from "../../../../../../@arbitrum/nitro-contracts/src/bridge/ISequencerInbox.sol/IFeeTokenPricer.js";

const _abi = [
  {
    inputs: [],
    name: "getExchangeRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFeeTokenPricer__factory {
  static readonly abi = _abi;
  static createInterface(): IFeeTokenPricerInterface {
    return new Interface(_abi) as IFeeTokenPricerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null,
  ): IFeeTokenPricer {
    return new Contract(address, _abi, runner) as unknown as IFeeTokenPricer;
  }
}
