/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ierc20Sol from "./IERC20.sol/index.js";
export * as iGatewaySol from "./IGateway.sol/index.js";
export * as iInitializableProxySol from "./IInitializableProxy.sol/index.js";
