/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from"./contracts/index.js";
export type { contracts };
import type * as contractsUpgradeable from"./contracts-upgradeable/index.js";
export type { contractsUpgradeable };
