/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc1363Sol from"./IERC1363.sol/index.js";
export type { ierc1363Sol };
import type * as ierc1967Sol from"./IERC1967.sol/index.js";
export type { ierc1967Sol };
import type * as ierc5267Sol from"./IERC5267.sol/index.js";
export type { ierc5267Sol };
import type * as draftIerc6093Sol from"./draft-IERC6093.sol/index.js";
export type { draftIerc6093Sol };
